### PR TITLE
Actualization libraries versions to compatible JDK17

### PR DESCRIPTION
**Pull request by altro3**
Upgrade libs:

Micronaut 3.3.1
Micronaut Docs 2.0.0
Groovy 3.0.9
Junit 5.8.2
Micronaut Sql 4.1.1
Micronaut Spring 4.0.1
Kotlin 1.6.10
Mockk 1.12.2
Kotest 4.6.4
AssertJ 3.22.0
Mockito 4.3.1
Hamcrest 2.2

For CI-CD changed versions:

Gradle 7.4
GraalVM 22.0.0.2
create-pull-request 3.12.1
Change JDK versions for test to 17

### CODE REVIEW

**Comment by altro3** [comment]
@graemerocher Hi! I think this pipeline (which failed) is wrong `GraalVM CE Native CI / build (java11) (pull_request)`. This is something old and `GraalVM CE CI / build (11) (pull_request)` pipeline replaced it, I think.

**Comment by graemerocher** [comment]
@altro3 I don't think so, this is https://github.com/micronaut-projects/micronaut-test/blob/master/.github/workflows/nativeTest.yml which runs the JUnit 5 tests natively

**Comment by altro3** [comment]
@graemerocher yeah, sorry, forgot to get last changes from master. I upgraded thi task to GraalVM 22.0.0.2 and actual github action plugins

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
