### PR TITLE
Use and export kotest-bom for kotest dependencies management

### LINKED ISSUE #843: kotest-bom should be used to manage kotest versions
### Feature description

Since version 5.x, kotest framework has a bom published: https://repo1.maven.org/maven2/io/kotest/kotest-bom/
Micronaut should use the bom to manage kotest versions. 
Especially taking into account that kotest has additional projects that are not managed by micronaut, but used by end users, like kotest-property. This requires from used to keep the versions of their additional kotest dependencies in sync with kotest modules brought by micronaut.

### PR DESCRIPTION
**Pull request by Spikhalskiy**
micronaut-test-kotest5 now uses and exposes kotest-bom

Related PR into micronaut-platform: https://github.com/micronaut-projects/micronaut-platform/pull/901
Closes #843

### CODE REVIEW

**Comment by Spikhalskiy** [comment]
Ideally explicit versions should be removed from

```
managed-kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "managed-kotest" }
managed-kotest-runner-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "managed-kotest" }
```

and
 
```
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "managed-junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "managed-junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "managed-junit" }
```

above it.

But when I try to do that I get 
```
* What went wrong:
Could not determine the dependencies of task ':micronaut-test-bom:build'.
> Could not create task ':micronaut-test-bom:assemble'.
   > Could not create task ':micronaut-test-bom:generateCatalogAsToml'.
      > A dependency constraint was added on 'io.kotest:kotest-assertions-core-jvm' without a version. This is invalid: a constraint must specify a version.
```

I guess these constraints are coming from an internal micronaut tooling ("io.micronaut.build.internal.bom" plugin?), but I didn't put time into figuring it out.

**Review by melix — CHANGES_REQUESTED** [review]
Can you move the `managed-kotest` entries back to where they were? They are intentionally grouped by `managed-`.

Thanks

**Comment by Spikhalskiy** [comment]
@melix done. I moved them into "managed-by-boms" group because I was going to drop the explicit specification of the version, but wasn't able to do that as described above. Moved them back.

**Comment by melix** [comment]
No, please keep them as is. Do not rename them as it's a breaking change. We use conventions, and these lead to properties in BOM files, or type-safe accessors in catalogs. Any change in the name is a breaking change. Thanks!

**Review by melix — APPROVED** [review]

**Review by timyates — APPROVED** [review]

**Pull request merged**
