### PR TITLE
Fix typo in file and classname

### PR DESCRIPTION
**Pull request by beedub**
Addresses https://github.com/micronaut-projects/micronaut-test/issues/55#issuecomment-517400821

### CODE REVIEW

**Comment by graemerocher** [comment]
Only change I think we have to make since 1.1 is already out is to add a deprecated version that extends the non deprecated version with the old name. So existing code doesn't break.

**Comment by beedub** [comment]
@graemerocher How does e80eef5 look? I'm new to kotlin so not sure if I'm doing it right!

**Comment by Kerooker** [comment]
Seems good to me

**Comment by graemerocher** [comment]
Nice, didn't know you could do typealiases with deprecation warnings. Pretty neat feature of Kotlin

**Comment by graemerocher** [comment]
Thanks for the PR!

**Pull request merged**
