### PR TITLE
Kotest 5.x.x support

### PR DESCRIPTION
**Pull request by Nandi**
Adds new module for Kotest 5.x.x #508

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks for the contribution, we will review soon

**Comment by sdelamo** [comment]
I plan to review this next week.

**Comment by Nandi** [comment]
@sdelamo any update on the review?

**Comment by BrianEstrada** [comment]
Bump for visiblity 👀 would be nice to be able to use Kotest5 in our projects

**Comment by graemerocher** [comment]
I will review and merge on Friday. Thanks for the patience

**Comment by graemerocher** [comment]
ok got delayed again, reviewing now

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
