### PR TITLE
use latest GraalVM

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Review by timyates — APPROVED** [review]
:+1: won't pass until https://github.com/micronaut-projects/micronaut-test/pull/618

**Comment by timyates** [comment]
I've applied the same change over there https://github.com/micronaut-projects/micronaut-test/pull/618

**Comment by alvarosanchez** [comment]
Isn't the common workflow "graalvm.yml" not enough for this project?

**Comment by timyates** [comment]
It seems not, as `test-junit5:nativeTest` was failing

**Review by alvarosanchez — APPROVED** [review]

**Pull request closed without merging**
