### PR TITLE
Pin Kotlin version to 1.3

### PR DESCRIPTION
**Pull request by alvarosanchez**

### CODE REVIEW

**Review by ilopmar — COMMENTED** [review]
Wouldn't it be better to do it in the `build` project so this change is propagated to all the projects? I know that not all of them use Kotlin, but there are a few of them than do it.

**Comment by alvarosanchez** [comment]
The thing is that pinning the version is temporary (as well as https://github.com/micronaut-projects/micronaut-kafka/pull/215). I'd like to get a patch release with Kotlin 1.3, then bump it to 1.4 and release micronaut-test 1.3

**Comment by graemerocher** [comment]
my concern would be we forget to remove these pinned versions. An associated issue needs to be created as reminder to revert the change.

**Comment by alvarosanchez** [comment]
@graemerocher in all projects, switching to a new minor or major should as well require to review and remove all pinned versions

**Pull request merged**
