### PR TITLE
Bump kotest version to 4.2.4

### PR DESCRIPTION
**Pull request by adamkobor**
Hey there, I would like to bump kotest's version to 4.2.4, because there are useful, new features in 4.2.x (i.e. container-level callbacks)

### CODE REVIEW

**Comment by ilopmar** [comment]
Thanks for the contribution. I've manually applied your changes and also upgrade the rest of the docs and the kotlin version in #293 and #294

**Comment by adamkobor** [comment]
Thanks for the heads-up!

**Comment by ilopmar** [comment]
btw @adamkobor it will be included in Micronaut Test 2.1.0 that will be the default in Micronaut 2.1.0

**Comment by adamkobor** [comment]
Thanks @ilopmar, I was assuming the same, since having different versions of Kotlin as a dependency in the same project would cause an issue anyways, AFAIK

**Pull request closed without merging**
