### PR TITLE
MicronautJunit5Extension: do not tear down application context in afterAll callback of nested test classes

### PR DESCRIPTION
**Pull request by angelyan**
Closes https://github.com/micronaut-projects/micronaut-test/issues/420

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Comment by angelyan** [comment]
@graemerocher is there a way for me to get this patch without having to wait for the next release? I've been wanting to use this feature for some time now.

**Comment by graemerocher** [comment]
Triggered a release https://github.com/micronaut-projects/micronaut-test/actions/runs/860975980

will be available soon

**Comment by angelyan** [comment]
Thanks!

**Pull request merged**
