### PR TITLE
Added junit-platform to managed block.

### PR DESCRIPTION
**Pull request by altro3**
Removed groovy and kotlin versions.
Fix logback for windows.
Minor fixes in dependencies.

### CODE REVIEW

**Comment by altro3** [comment]
@dstepanov Look to this, pls. junit-platform uses in micronaut-jax-rs. I think, it's better to add these libraries to versions catalog

**Comment by dstepanov** [comment]
@sdelamo @melix Please check

**Review by melix — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
@altro3  can you merge 4.6.x into this PR?

**Comment by altro3** [comment]
@sdelamo done

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
