### PR TITLE
build: enable testNative

### PR DESCRIPTION
**Pull request by sdelamo**
@graemerocher do you know about this error: 

```
The bundle named: org.glassfish.jaxb.runtime.v2.model.impl.Messages, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.

Fatal error: java.lang.IllegalArgumentException: duplicate element: ALL_PUBLIC_METHODS
        at java.base/java.util.ImmutableCollections$SetN.<init>(ImmutableCollections.java:918)
        at java.base/java.util.Set.of(Set.java:706)
        at io.micronaut.core.graal.GraalReflectionConfigurer.lambda$configure$3(GraalReflectionConfigurer.java:65)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.micronaut.core.graal.GraalReflectionConfigurer.configure(GraalReflectionConfigurer.java:59)
        at io.micronaut.core.io.service.ServiceLoaderFeature.configureForReflection(ServiceLoaderInitialization.java:208)
        at io.micronaut.core.io.service.ServiceLoaderFeature.beforeAnalysis(ServiceLoaderInitialization.java:62)
------------------------------------------------------------------------------------------------------------------------
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
                        0.6s (5.1% of total time) in 11 GCs | Peak RSS: 1.00GB | CPU load: 2.55
===================================================================================================
```

### CODE REVIEW

**Comment by sdelamo** [comment]
@graemerocher 

> seems like a bug in our code not in GraalVM
> here are duplicate entries for accessType somewhere https://github.com/micronaut-projects/micronaut-core/blob/72b1a7eea8717630b796959855944b10a4361d43/core/src/main/java/io/micronaut/core/graal/GraalReflectionConfigurer.java#L66

**Comment by sdelamo** [comment]
Probably fixed by https://github.com/micronaut-projects/micronaut-core/pull/9015

**Comment by sdelamo** [comment]
@timyates can you merge master against this branch and see if it works.

**Comment by timyates** [comment]
Still fails...  Seems spock is getting on to the native classpath somehow...

**Comment by timyates** [comment]
Pushed a fix to exclude spock from the nativeImageTestClasspath https://github.com/micronaut-projects/micronaut-test/pull/733/commits/c9d1daac149a5636f23d399cc4231013202dbadc

I assume it's our build plugin that's adding it...  I still can't read the dependencies tab in Gradle enterprise

**Pull request merged**
